#!/usr/bin/env bash
#Installling and configuring HAproxy on lb-01 server(third one)

echo -e "Updating server properties AND PURPOSE....\n"

function install() {
	command -v "$1" &> /dev/null

	#disable=SC2181 / disabling shellcheck, first server properties
	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

install haproxy #install haproxy

echo -e "\nSetting up even more stuff \n"

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 6162-web-01 34.224.56.2:80 check
    server 6162-web-02 54.147.169.8:80 check
"
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi

echo -e "web-01 web-02"
echo "web-01"
echo "web-02"
