#!/usr/bin/env bash
#this script is for transfering files from server to server

if [$# - lt 4]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
#parameters for user usage
file="$1"
host="$2"
user="$3"
ssh_key_public="$4"

#transfer the data from server to server(username is scp)
scp -o "StrictHostKeyChecking=no" -i "$ssh_key_public" "$file" "$user"@"$host":~
exit 0