#!/usr/bin/env bash
#configures nginx server so that /redirect_me is redirecting to other page
#redirection must be "301 Moved Permanently"

sudo apt-get -y install nginx
sudo bash -c 'echo "Holberton School" > /var/www/html/index.nginx-debian.html'

redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart